name: Test Reqfleet Action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run Reqfleet Action
        uses: reqfleet/actions@v0.1.3 # https://github.com/marketplace/actions/reqfleet-tests-action
        id: reqfleet # Assign an ID to the step to access its outputs
        with:
          collection_id: 'your collection_id'
          api_key: ${{ secrets.REQFLEET_API_KEY }} # Use a GitHub Secret for your API key
          fail_on_over_threshold: true
          latency_threshold: 'avg:100ms,p90:150ms,p95:200ms,p99:300ms'

      - name: Get Reqfleet Action Outputs
        run: |
          echo "Summary Output: ${{ steps.reqfleet.outputs.summary }}"
          # echo "Raw Metrics Output: ${{ steps.reqfleet.outputs.raw_metrics_output }}" # This output has been removedo
